name: CI/CD newyork-server

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - "v*"
  pull_request:
    branches:
      - "dev"

env:
  REGISTRY: ghcr.io
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ${{ github.repository }}
jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add rustfmt

      - name: Cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: |
          cd ./newyork-server
          touch .env.staging
          echo HCMC_HOST=${{secrets.HCMC_HOST}} >> .env.staging
          echo ALCHEMY_API=${{secrets.ALCHEMY_API}} >> .env.staging

          touch .env.test
          echo TEST_EMAIL=${{secrets.TEST_EMAIL}} >> .env.test
          echo TEST_PASS=${{secrets.TEST_PASS}} >> .env.test
          echo TEST_SIGNIN_URL=${{secrets.TEST_SIGNIN_URL}} >> .env.test
          cargo fmt
          cargo test --verbose
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cd ./newyork-server
          touch .env.staging
          echo HCMC_HOST=${{secrets.HCMC_HOST}} >> .env.staging
          echo ALCHEMY_API=${{secrets.ALCHEMY_API}} >> .env.staging

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./newyork-server
          push:  ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker deploy
        if: github.event_name != 'pull_request'
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          envs: IMAGE_NAME
          script: |
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ${{ env.REGISTRY }} -u ${{ github.repository }} --password-stdin
            echo ${{ steps.meta.outputs.tags }}
            docker pull ${{ steps.meta.outputs.tags }}
            cd $HOME && \
            docker network create --driver bridge tss_new || true && \
            docker stop nyc || true && docker rm nyc || true && \
            docker run --restart unless-stopped -d --name nyc --ip ${{secrets.NYC_CONTAINER_IP}} -p ${{secrets.NYC_PORT}}:${{secrets.NYC_PORT}} --network=tss_new ${{ steps.meta.outputs.tags }}
